// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for generating business insights and recommendations using AI.
 *
 * - generateBusinessInsights - A function that triggers the business insights generation flow.
 * - GenerateBusinessInsightsInput - The input type for the generateBusinessInsights function.
 * - GenerateBusinessInsightsOutput - The return type for the generateBusinessInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateBusinessInsightsInputSchema = z.object({
  totalRevenue: z.number().describe('The total revenue for the selected period.'),
  totalExpenses: z.number().describe('The total expenses for the selected period.'),
  netProfit: z.number().describe('The net profit for the selected period.'),
  orderCount: z.number().describe('The total number of orders for the selected period.'),
  clientAcquisitionRate: z
    .number()
    .describe('The rate of new client acquisition for the selected period.'),
  repeatClientRate: z
    .number()
    .describe('The rate of repeat clients for the selected period.'),
  averageOrderValue: z
    .number()
    .describe('The average order value for the selected period.'),
  monthlyTargetRevenue: z.number().describe('The monthly target revenue.'),
  averageDailyRevenue: z.number().describe('The average daily revenue.'),
  requiredDailyRevenue: z.number().describe(
    'The required daily revenue to meet the monthly target.'
  ),
  dailyRevenueTrendGraph: z
    .string()
    .describe('A data URI representing the daily revenue trend graph.'),
  netProfitGraph: z.string().describe('A data URI representing the net profit graph.'),
  incomeBySourceChart: z.string().describe('A data URI representing the income by source chart.'),
  competitorOrderCount: z
    .number()
    .describe('The average order count of competitors for the selected period.'),
  additionalNotes: z.string().optional().describe('Additional notes about the business.'),
});

export type GenerateBusinessInsightsInput = z.infer<
  typeof GenerateBusinessInsightsInputSchema
>;

const GenerateBusinessInsightsOutputSchema = z.object({
  insights: z.string().describe('AI-generated insights and recommendations.'),
});

export type GenerateBusinessInsightsOutput = z.infer<
  typeof GenerateBusinessInsightsOutputSchema
>;

export async function generateBusinessInsights(
  input: GenerateBusinessInsightsInput
): Promise<GenerateBusinessInsightsOutput> {
  return generateBusinessInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateBusinessInsightsPrompt',
  input: {schema: GenerateBusinessInsightsInputSchema},
  output: {schema: GenerateBusinessInsightsOutputSchema},
  prompt: `You are an AI-powered business consultant. Analyze the following business data and provide insights and recommendations to improve business performance.

Business Data:
Total Revenue: {{{totalRevenue}}}
Total Expenses: {{{totalExpenses}}}
Net Profit: {{{netProfit}}}
Order Count: {{{orderCount}}}
Client Acquisition Rate: {{{clientAcquisitionRate}}}
Repeat Client Rate: {{{repeatClientRate}}}
Average Order Value: {{{averageOrderValue}}}
Monthly Target Revenue: {{{monthlyTargetRevenue}}}
Average Daily Revenue: {{{averageDailyRevenue}}}
Required Daily Revenue: {{{requiredDailyRevenue}}}
Competitor Order Count: {{{competitorOrderCount}}}

Charts:
Daily Revenue Trend Graph: {{media url=dailyRevenueTrendGraph}}
Net Profit Graph: {{media url=netProfitGraph}}
Income by Source Chart: {{media url=incomeBySourceChart}}

Additional Notes: {{{additionalNotes}}}

Provide actionable insights and recommendations based on the provided data. Focus on areas for improvement, and strategies to increase revenue and profitability.`,
});

const generateBusinessInsightsFlow = ai.defineFlow(
  {
    name: 'generateBusinessInsightsFlow',
    inputSchema: GenerateBusinessInsightsInputSchema,
    outputSchema: GenerateBusinessInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
